Repository AY2324S2-CS2103T-F10-2/tp, pull requests merged in 2024-03, with the labels that each got.

#48 Viewing of Summary Stats - Total Student Count
  docs/index.md
  src/main/java/.idea/checkstyle-idea.xml
  src/main/java/.idea/misc.xml
  src/main/java/.idea/modules.xml
  src/main/java/.idea/vcs.xml
  src/main/java/main.iml
  src/main/java/out/production/main/.idea/checkstyle-idea.xml
  src/main/java/out/production/main/.idea/misc.xml
  src/main/java/out/production/main/.idea/modules.xml
  src/main/java/out/production/main/.idea/vcs.xml
  src/main/java/out/production/main/main.iml
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SummaryStatsWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SummaryStatsWindow.css
  src/main/resources/view/SummaryStatsWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#61 Fix Logic Manager Tests and Edit EditCommand class to edit subject
  build.gradle
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug

#86 Payment method
  out.txt
  src/main/java/out/production/main/.idea/.gitignore
  src/main/java/out/production/main/.idea/checkstyle-idea.xml
  src/main/java/out/production/main/.idea/misc.xml
  src/main/java/out/production/main/.idea/modules.xml
  src/main/java/out/production/main/.idea/vcs.xml
  src/main/java/out/production/main/main.iml
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddPaymentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkPaymentCommand.java
  src/main/java/seedu/address/logic/commands/ResetPaymentsCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddPaymentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkPaymentCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ResetPaymentsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Id.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPaymentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkPaymentCommandTest.java
  src/test/java/seedu/address/logic/commands/ResetPaymentsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddPaymentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkPaymentCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ResetPaymentsCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalIds.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High
